friend/urls.py
from django.conf.urls import url
from friend.views import *

urlpatterns = [
    # url(r'^$',sign_in,name='sign_in'),
     url(r'^$',log_in,name='login'),
     url(r'^test$',test,name='test'),
     url(r'^signup$',register,name='signup'),
     url(r'^index$',after_login,name='afterlogin'),
     url(r'^subaff$',sub_affair,name='subaffair'),
     url(r'^addfri$',add_friend,name='add_friend'),
     url(r'^friadd$',friend_add,name='friend_add'),
     url(r'^logout$',log_out,name='logout'),

     url(r'^quxiao$',quxiao,name='quxiao'),
     url(r'^testtwo$',testtwo,name='testtwo'),
     url(r'^seting$',seting,name='seting'),
     url(r'^alter$',seting_alter,name='seting_alter'),
     url(r'^history/(?P<user_id>[0-9]+)$',history,name='history'),


]

helfriend/urls.py
from django.conf.urls import url,include
from django.contrib import admin
from friend import urls as friend_urls
urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'',include(friend_urls,namespace='friend')),
]

friend/models.py
from __future__ import unicode_literals

from django.db import models
from django.contrib.auth.models import AbstractUser

class FriUser(AbstractUser):
      signature = models.CharField(default='this guy is lazy to leave something'                  ,max_length=256)
      friends_id = models.CharField(null=True,max_length=256)
      add_fri_id = models.CharField(null=True,blank=True,max_length=256)
      email_address = models.CharField(max_length=256)
      phone = models.CharField(null=True,blank=True,max_length=256)

      def __unicode__(self):
           return self.username

class Affair(models.Model):
      author = models.ForeignKey('FriUser')
      content = models.TextField()
      pub_date = models.DateTimeField(auto_now_add=True,editable=True)
      like_count = models.IntegerField(default=0)
      
      def __unicode__(self):
           return self.content

class Comment(models.Model):
      affair = models.ForeignKey('Affair')
      content = models.TextField()
      pub_date = models.DateTimeField(auto_now_add=True,editable=True)
      author = models.ForeignKey('FriUser')

     
class Upload(models.Model):
      user = models.OneToOneField(FriUser) 
      image  = models.ImageField( upload_to='friend/media/',default='friend/media/no_img.jpg')

friend/forms.py
from django import forms

from friend.models import *

class LoginForm(forms.Form):
     uid = forms.CharField(widget=forms.TextInput(attrs={'class':'form-control',   'id':'uid','placeholder':'Username'}))
     pwd = forms.CharField(widget=forms.PasswordInput(attrs={'class':'form-control',   'id':'pwd','placeholder':'Password'}))

class RegisterForm(forms.Form):
       username = forms.CharField(widget=forms.TextInput(attrs={'class':'form-control',
   'id':'uid','placeholder':'Username'}))
       password1 = forms.CharField(widget=forms.PasswordInput(attrs={'class':'form-control',   'id':'pwd','placeholder':'Password'}))
       password2 = forms.CharField(widget=forms.PasswordInput(attrs={'class':'form-control',   'id':'pwd','placeholder':'Password'}))

class UploadForm(forms.ModelForm):
      class Meta:
            model = Upload
            fields = ['image']

friend/views.py
# -*- coding:utf8 -*-
from django.shortcuts import render

# Create your views here.
from django.contrib.auth import login,logout,authenticate
from django.contrib.auth import login,logout,authenticate
from django.core.urlresolvers import reverse
from django.shortcuts import render,redirect,get_object_or_404

from django.core.exceptions import ObjectDoesNotExist

from friend.forms import *
from django.http import HttpResponse ,HttpResponseRedirect
from friend.models import *
def sign_in(request):
    return render(request,'friend/sign_in.html')

def log_in(request):
    if request.method == 'GET':
       form = LoginForm()
       return render(request,'friend/sign_in.html',{'form':form})
    else:
       form = LoginForm(request.POST)
       if form.is_valid():
            username = form.cleaned_data['uid']
            password = form.cleaned_data['pwd']
            user = authenticate(username=username,password=password)
            if user  and user.is_active:
               login(request,user)
               return redirect(reverse('friend:afterlogin'))
            else:
               msg = 'username or password is not true!'
               return render(request,'friend/sign_in.html',{'form':form,'msg':msg})
       else:
             msg = 'the format is not correct!'
             return render(request,'friend/sign_in.html',{'form':form,'msg':msg})
def test(request):
    return render(request,'friend/test.html')



def register(request):
      if request.method == 'GET':
         form = RegisterForm()
         return render(request,'friend/sign_up.html',{'form':form})
      else:
         form = RegisterForm(request.POST)
         if form.is_valid():
            username = form.cleaned_data['username']
            password1 = form.cleaned_data['password1']
            password2 = form.cleaned_data['password2']
            try:
               user =  FriUser.objects.get(username=username)
            except ObjectDoesNotExist:
               if password1 != password2:
                  msg = 'two password is not same!'
                  return render(request,'friend/sign_up.html',{'form':form,'msg':msg})
               else:
                   newuser = FriUser()
                   newuser.username = username
                   newuser.set_password(password1)
                   newuser.save()
                   login(request,newuser)
                   return redirect(reverse('friend:afterlogin'))
            else:
                msg = 'the username is already exist!'
                return render(request,'friend/sign_up.html',{'form':form,'msg':    msg})
         else:
             msg = 'format is not correct!'
             return render(request,'friend/sign_up.html',{'form':form,'msg':msg    })

def after_login(request):
        add_id_list = str_to_list(request.user.add_fri_id)
        try:
             add_id_list.remove('')
        except:
               pass
        if add_id_list is None:
            affair_set = request.user.affair_set.all()
            fri_id_list = str_to_list(request.user.friends_id)
            global userlist
            userlist = []
            try:
                fri_id_list.remove('')
            except:
                pass
            if fri_id_list is not None:
                
                for fri_id in fri_id_list:
                    user = FriUser.objects.get(id=int(fri_id))
                    userlist.append(user)
                    affair_set = affair_set | user.affair_set.all()  
                    fri_id_list_again = str_to_list(user.friends_id)
                    
                    try:
                       fri_id_list_again.remove('')
                    except:
                         pass
                    if fri_id_list_again is not None:
                        for fri_id_again in fri_id_list_again:
                            user_again = FriUser.objects.get(id=int(fri_id_again                            ))
                            affair_set = affair_set | user_again.affair_set.all(                            )
                             


            affair_set = affair_set.order_by('-pub_date')
            dictionary = {'affair_set':affair_set,'userlist':userlist}
            return render(request,'friend/main.html',dictionary)
        else:
               userlist = []
               for i in add_id_list:
                    user = FriUser.objects.get(id=int(i))
                    userlist.append(user)
               return render(request,'friend/friend_add.html',
                            {'userlist':userlist})                 
                    
def sub_affair(request):
    if request.method == 'POST':
        newaffair = Affair()
        newaffair.author = request.user
        newaffair.content = request.POST['affair_sub']
        newaffair.save()
        return redirect(reverse('friend:afterlogin'))
    else:
        return render(request,'friend/fabiao.html',{'userlist':userlist})

def add_friend(request):
        if request.method == 'GET':
             return render(request,'friend/add_friend.html',{'userlist':userlist})
        else:
            try: 
                  this_user = request.user
                  that_user = FriUser.objects.get(username=request.POST['username'])
                  friend_id_list = str_to_list(this_user.friends_id)
                  if (friend_id_list is  None) or(str(that_user.id) not in                         friend_id_list) :
                      
                       add_fri_id_list = str_to_list(that_user.add_fri_id)
                       if add_fri_id_list is not None:
                       
                           add_fri_id_list.append(str(this_user.id))
                           that_user.add_fri_id = ','.join(set(add_fri_id_list))
                       else:
                           that_user.add_fri_id = str(this_user.id)

                       that_user.save()
                       return redirect(reverse('friend:afterlogin'))
                  else:
                       msg = '该用户已经是您的好友'
                       return render(request,'friend/add_friend.html',{'userlist':userlist,'msg':msg})
            except:
                  msg = '该用户不存在'
                  return render(request,'friend/add_friend.html',{'msg':msg, 'userlist':userlist})

                        
def quxiao(request):
    return redirect(reverse('friend:afterlogin'))


def str_to_list(string):
        if string is None:
               return None
        else:
               return string.split(',')
       
def testtwo(request):
     receive = request.POST.getlist('vehicle')
     return HttpResponse(receive[1])

def  friend_add(request):
      userids = request.GET.getlist('username') 
      friends_id_list = str_to_list(request.user.friends_id)
      if friends_id_list is None:
           friends_id_list = userids
      else:
          friends_id_list = friends_id_list + userids
      request.user.friends_id = ','.join(set(friends_id_list))
      request.user.add_fri_id = None
      request.user.save()
      for i in userids:
             user = FriUser.objects.get(id=int(i))
             idlist = str_to_list(user.friends_id)
             if idlist is None:
                  user.friends_id = request.user.id
             else:
                  idlist.append(str(request.user.id))
                  user.friends_id = ','.join(set(idlist))
             user.save()           
      return redirect(reverse('friend:afterlogin'))

def log_out(request):
       logout(request)
       return redirect(reverse('friend:login'))

def seting(request):
       if request.method == 'GET':
           return render(request,'friend/seting.html',{'userlist':userlist})
       else:
            pass


def seting_alter(request):
       if request.method == 'GET':
           return render(request,'friend/seting_alter.html',{'user':request.user             ,'userlist':userlist  } )
       else:
            return HttpResponse('hello')


def history(request,user_id):
      user = FriUser.objects.get(id=user_id)
      affairset = user.affair_set.order_by('pub_date')
      form = {'user':user,'affairset':affairset,'userlist':userlist}
      return render(request,'friend/history.html',form)

friend/templates/friend/add_friend.html
{% extends 'friend/main.html' %}

{% block page %}
  <h3>{{msg}}</h3>
<form method='post' action="{% url 'friend:add_friend' %}">
   {% csrf_token %}
   <input type='text' name='username' />
   <input type='submit' value='添加' />
   <a href="{% url 'friend:quxiao' %}">取消</a>

{% endblock %}

friend/templates/friend/base.html
<head></head>
{% block content%}

{% endblock %}

friend/templates/friend/fabiao.html
{% extends 'friend/main.html' %}
{% load staticfiles %}
{% block page %}

  <script src="{% static 'friend/js/tinymce/tinymce.min.js' %}"></script>
  <script>tinymce.init({ selector:'textarea' });</script>
  <form method='post' action="{% url 'friend:subaffair' %}">
     {% csrf_token %}
     <textarea name='affair_sub'></textarea>
     <input type='submit',value='Save' />
  </form>
{% endblock %}

friend/templates/friend/friend_add.html
{% extends 'friend/main.html' %}

{% block page %}
<form  method='get' action="{% url 'friend:friend_add' %}">
<h2>以下用户请求加您为好友</h2>
  {% for user in userlist %}
    <p>{{user.username}}</p>
    <input type="checkbox" name="username" value="{{user.id}}" checked="checked" />
    <br />
    <br /><br />
    <input type="submit" value="Submit" />
  {% endfor %}
<a href="{ url 'friend:bujieshou' %}" >全不添加</a>
</form> 

{% endblock %}

friend/templates/friend/history.html
{% extends 'friend/main.html' %}

{% block page %}
<div>{{ user.username }}的发表历史:</div>
   <hr>
   {% for affair in affairset %}
    <p>{{ affair.content | safe }}</p>
            <p> {{affair.pub_date }}</p>
     <hr>
   {% endfor %}
  

{% endblock %}

friend/templates/friend/main.html
{% load staticfiles %}
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">
    <link rel="icon" href="../../favicon.ico">

    <title>让我们更近一步~</title>
    <link href="{% static 'friend/css/bootstrap.min.css' %}" rel="stylesheet">
    <link href="{% static 'friend/css/navbar-fixed-top.css' %}" rel="stylesheet">


    <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js"></script>
      <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->
  </head>

  <body>

    <!-- Fixed navbar -->
    <nav class="navbar navbar-default navbar-fixed-top">
      <div class="container">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" href="{% url 'friend:afterlogin' %}">helfriend</a>
        </div>
        <div id="navbar" class="navbar-collapse collapse">
          <ul class="nav navbar-nav">
            <li class=""><a href="{% url 'friend:subaffair' %}">发表</a></li>
            <li class=""><a href="{% url 'friend:add_friend' %}">加好友</a></li>
          </ul>
          <ul class="nav navbar-nav navbar-right">
            <li class=""><a href="#">欢迎</a></li>
            <li class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">{{request.user.username}} <span class="caret"></span></a>
              <ul class="dropdown-menu">
                <li><a href="{% url 'friend:seting' %}">个人中心</a></li>
                <li><a href="{% url 'friend:logout' %}">退出</a></li>
                
              <li role="separator" class="divider"></li> 

             <li class="dropdown-header">好友列表</li>

                {% for user in userlist %}
                <li><a href="{% url 'friend:history' user.id %}">{{user.username}}</a></li>
                {% endfor %}
              </ul>
            </li>
          </ul>
      </div>
    </nav>
 {% block container %}
    <div class="container">
    
      <!-- Main component for a primary marketing message or call to action -->
      <div class="jumbotron">
         {% block page %}

         {% for affair in affair_set %}
           <a color='blue' href="{% url 'friend:history' affair.author.id %}">{{ affair.author }}</a>
           <p>{{ affair.content | safe }}</p>
            <p> {{affair.pub_date }}</p>
           <hr>

         {% endfor %}
      </div>
     {% endblock %}
    </div> <!-- /container -->

{% endblock %}
    <!-- Bootstrap core JavaScript
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    <script src="{% static 'friend/js/jquery.min.js' %}"></script>
    <script src="{% static 'friend/js/bootstrap.min.js' %}"></script>
  </body>
</html>

friend/templates/friend/seting.html
{% extends 'friend/main.html' %}
{% load staticfiles %}
{% block container %}
<html lang="zh-CN">
<meta charset='utf-8' />

<link rel="stylesheet" href="{% static 'friend/css/z.755d7b1e.css' %}">

<link rel="stylesheet" href="{% static 'friend/css/main.0eaf7d34.css' %}">


<div class="zg-wrap zu-main clearfix no-sidebar"  role="main">
<div class="zu-main-content">
<div class="zu-main-content-inner">




<ul class="tab-navs">
<li class="tab-nav active">
<a href="/settings/profile">基本资料</a>
</li>
<li class="tab-nav">
<a href="/settings/account">帐号和密码</a>
</li>
<li class="tab-nav">
<a href="/settings/notification">消息和邮件</a>
</li>
<li class="tab-nav">
<a href="/settings/filter">屏蔽</a>
</li>

</ul>

{% block seting %}

<div class="settings-section">
<div class="settings-item clearfix">
<label for="fullname" class="settings-item-title">姓名</label>
<div class="settings-item-content rename-section" id="rename-section">
<span class="name">{{user.username}}</span>
</div>
</div>

<div class="settings-section">
<div class="settings-item clearfix">
<label for="fullname" class="settings-item-title">邮箱</label>
<div class="settings-item-content rename-section" id="rename-section">
<span class="name">{{user.email_adress}}</span>
</div>
</div>

<div class="settings-section">
<div class="settings-item clearfix">
<label for="fullname" class="settings-item-title">手机</label>
<div class="settings-item-content rename-section" id="rename-section">
<span class="name">{{user.phone}}</span>
</div>
</div>

<div class="settings-section">
<div class="settings-item clearfix">
<label for="fullname" class="settings-item-title">个性签名</label>
<div class="settings-item-content rename-section" id="rename-section">
<span class="name">{{user.signature}}</span>
</div>
</div>

<div class="settings-save">
<a class="zg-btn-blue" href="{% url 'friend:seting_alter' %}">修改</a>
</div>

{% endblock %}


<div class="settings-item clearfix">
<label for="url_token" class="settings-item-title with-input">个性域名</label>
<div class="settings-item-content">

<input autocomplete="off" class="zg-form-text-input" name="url_token" id="url_token" value="lin-fa-jian" required>
</div>
</div>


</div>
</div>
</div>
{% endblock %}

friend/templates/friend/seting_alter.html
{% extends 'friend/seting.html' %}



{% block seting %}

<form action="/index" method="POST" class="zm-settings-account" id="js-settings-account-form" autocomplete="off">
{% csrf_token %}
<div class="settings-item clearfix">
<label for="url_token" class="settings-item-title with-input">用户名</label>
<div class="settings-item-content">

<input autocomplete="off" class="zg-form-text-input" name="url_token" id="url_token" value={{user.username}} required>
</div>
</div>

<div class="settings-item clearfix">
<label for="url_token" class="settings-item-title with-input">邮箱</label>
<div class="settings-item-content"> 

<input autocomplete="off" class="zg-form-text-input" name="url_token" id="url_token" value={{user.email_address}} required>
</div>
</div>

<div class="settings-item clearfix">
<label for="url_token" class="settings-item-title with-input">手机</label>
<div class="settings-item-content"> 

<input autocomplete="off" class="zg-form-text-input" name="url_token" id="url_token" value={{user.phone}} required>
</div>
</div>

<div class="settings-item clearfix">
<label for="url_token" class="settings-item-title with-input">个性签名</label>
<div class="settings-item-content"> 

<input   name="url_token" type='text'  value={{user.signature}} >
</div>
</div>


<div class="settings-save">
<button type="submit" class="zg-btn-blue">保存</button>
</div>

</form>

{% endblock %}

friend/templates/friend/sign_in.html
{% load staticfiles %}
<!DOCTYPE html>
<!-- saved from url=(0040)http://getbootstrap.com/examples/signin/ -->
<html lang="en"><head><meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
    
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->
    <meta name="description" content="">
    <meta name="author" content="">
    <link rel="icon" href="http://getbootstrap.com/favicon.ico">

    <title>Signin Template for Bootstrap</title>

    <!-- Bootstrap core CSS -->
    <link href="{% static 'friend/css/bootstrap.min.css' %}" rel="stylesheet">

    <!-- IE10 viewport hack for Surface/desktop Windows 8 bug -->
    <link href="{ static 'friend/css/signin.css" rel="stylesheet">

    <!-- Custom styles for this template -->
    <link href="{% static 'friend/css/signin1.css' %}" rel="stylesheet">

    <!-- Just for debugging purposes. Don't actually copy these 2 lines! -->
    <!--[if lt IE 9]><script src="../../assets/js/ie8-responsive-file-warning.js"></script><![endif]-->
    <script src="{% static 'friend/js/signin1.js' %}"></script>

    <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
    <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js"></script>
      <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->
  </head>

  <body>

    <div class="container">
      {% block content %}
      <form class="form-signin" action='{% url "friend:login" %}' method='post'>
          {% csrf_token %}
        <h2 class="form-signin-heading">Please sign in</h2>
        {{ msg }}
        {{ form.uid }}
        {{ form.pwd }}
        <div class="checkbox">
          <label>
            <input type="checkbox" value="remember-me"> Remember me
          </label>
        </div>
        <input class="btn btn-lg btn-primary btn-block" type="submit"  value='sign in' />
        <a href="{% url 'friend:signup' %}" class="btn btn-lg btn-primary btn-block" title='sign_up' >sign up</a>
       {% endblock %}
      </form>

    </div> <!-- /container -->


    <!-- IE10 viewport hack for Surface/desktop Windows 8 bug -->
    <script src="{% static 'friend/js/sign.js' %}"></script>
  

friend/templates/friend/sign_up.html
{% load staticfiles %}
<!DOCTYPE html>
<!-- saved from url=(0040)http://getbootstrap.com/examples/signin/ -->
<html lang="en"><head><meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
    
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->
    <meta name="description" content="">
    <meta name="author" content="">
    <link rel="icon" href="http://getbootstrap.com/favicon.ico">

    <title>Signin Template for Bootstrap</title>

    <!-- Bootstrap core CSS -->
    <link href="{% static 'friend/css/bootstrap.min.css' %}" rel="stylesheet">

    <!-- IE10 viewport hack for Surface/desktop Windows 8 bug -->
    <link href="{ static 'friend/css/signin.css" rel="stylesheet">

    <!-- Custom styles for this template -->
    <link href="{% static 'friend/css/signin1.css' %}" rel="stylesheet">

    <!-- Just for debugging purposes. Don't actually copy these 2 lines! -->
    <!--[if lt IE 9]><script src="../../assets/js/ie8-responsive-file-warning.js"></script><![endif]-->
    <script src="{% static 'friend/js/signin1.js' %}"></script>

    <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
    <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js"></script>
      <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->
  </head>

  <body>

    <div class="container">
      {% block content %}
      <form class="form-signin" action='' method='post'>
          {% csrf_token %}
        <h2 class="form-signin-heading">Please sign up</h2>
         {{ msg }}
        {{ form.username }}
         <br>
        {{ form.password1 }}
        {{ form.password2 }}
        <input class="btn btn-lg btn-primary btn-block" type="submit"  value='sign up' />
       {% endblock %}
      </form>

    </div> <!-- /container -->


    <!-- IE10 viewport hack for Surface/desktop Windows 8 bug -->
    <script src="{% static 'friend/js/sign.js' %}"></script>
  

friend/templates/friend/test.html
{% load staticfiles %}

<html>
  <form method='post' action=''>
   {% csrf_token %}
  <input type='file' name='select'/>
 <input type='submit' value='tijiao'/>

</form>

<img src="/static/friend/media/no_img.jpg">

</html>
